fixes:
    - "ballerina/graphql/**/::../ballerina/"
    - "io/ballerina/stdlib/graphql/compiler/::./compiler-plugin/src/main/java/io/ballerina/stdlib/graphql/compiler/"
    - "io/ballerina/stdlib/graphql/commons/::./commons/src/main/java/io/ballerina/stdlib/graphql/commons/"

ignore:
    - "ballerina-tests"

coverage:
    precision: 2
    round: down
    range: "60...80"
    status:
        project:
            default:
                target: 80
