[[dependency]]
org = "ballerina"
name = "auth"
version = "1.1.0-beta.1"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-beta.1"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.1"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-beta.1"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "1.1.0-beta.1"

[[dependency]]
org = "ballerina"
name = "oauth"
version = "1.1.0-beta.1"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-beta.1"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-beta.1"
