[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-alpha8"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha8"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha8"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-alpha8"
