[package]
org = "ballerina"
name = "graphql"
version = "1.0.1"
authors = ["Ballerina"]
keywords = ["GraphQL", "gql"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/graphql-native-1.0.1-SNAPSHOT.jar"
