[package]
org = "ballerina"
name = "graphql"
version = "1.1.1"
authors = ["Ballerina"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
license = ["Apache-2.0"]
distribution = "slbeta6"

[[platform.java11.dependency]]
path = "../native/build/libs/graphql-native-1.1.1.jar"
