[package]
org = "ballerina"
name = "graphql"
version = "1.4.5"
authors = ["Ballerina"]
keywords = ["gql", "network", "query", "service"]
repository = "https://github.com/ballerina-platform/module-ballerina-graphql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-native"
version = "1.4.5"
path = "../native/build/libs/graphql-native-1.4.5-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "graphql-compiler-plugin"
version = "1.4.5"
path = "../compiler-plugin/build/libs/graphql-compiler-plugin-1.4.5-SNAPSHOT.jar"
