name: Build

on:
    push:
        branches:
            - master
        paths-ignore:
            - '*.md'
            - 'docs/**'
            - 'load-tests/**'

    workflow_dispatch:

jobs:
    call_stdlib_workflow:
        name: Run StdLib Workflow
        if: ${{ github.repository_owner == 'ballerina-platform' }}
        uses: ballerina-platform/ballerina-standard-library/.github/workflows/build-timestamp-master-template.yml@main
