name: Publish Release

on:
    workflow_dispatch:
    repository_dispatch:
        types: [ stdlib-release-pipeline ]

jobs:
    call_stdlib_workflow:
        name: Run StdLib Workflow
        if: ${{ github.repository_owner == 'ballerina-platform' }}
        uses: ballerina-platform/ballerina-standard-library/.github/workflows/release-package-template.yml@main
        with:
            package-name: graphql
            package-org: ballerina
            additional-build-flags: '-x :graphql-examples:build'
